# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='movies.Movie'),
        ),
    ]
