# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('place', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='seances.Seance')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set([('row', 'place', 'seance')]),
        ),
    ]
