# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='seances.Seance'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set([('row', 'place', 'seance')]),
        ),
    ]
